services:
  php:
    build:
      context: ./php
    container_name: campus-facility-reporting_php
    volumes:
      - ./src:/var/www/html
    environment:
      - PROJECT_NAME=campus-facility-reporting
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "composer", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: ./nginx
    container_name: campus-facility-reporting_nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - php
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --show-error --fail --insecure https://campus-facility-reporting.test/up || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mariadb:10.11
    container_name: campus-facility-reporting_db
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: campus-facility-reporting
      MYSQL_ROOT_PASSWORD: p455w0rd
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
#untuk menghungungkan ke database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: campus-facility-reporting_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: p455w0rd
    ports:
      - "8080:80"
    depends_on:
      - db
